server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    include:
      - domain

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

api:
  service-key: ${SERVICE_KEY}
  service-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst