server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    include:
      - weather-domain

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always